### ISSUE TITLE
Strapi bootstrap

### ISSUE THREAD

**Issue by lakaniemi** [Tietokilta/tikweb-cms#8]
## Description

Strapi project setup, see [docs](https://strapi.io/documentation/developer-docs/latest/installation/cli.html).

It would be good to create a base for configuration in different environments. See [docs](https://strapi.io/documentation/developer-docs/latest/concepts/configurations.html#environments). The main question is probably the database. We can:
* Use sqlite locally and e.g. postgres in production
* Use the same database locally as in production. In this case we have to set up some way of running e.g. postgres locally (docker?)

Strapi's TypeScript support seems to be quite bad right now. There's a pretty recent [PR](https://github.com/strapi/strapi/pull/9076) related to this. There's also this [roadmap entry](https://portal.productboard.com/strapi/1-roadmap/c/30-support-typescript) without a time estimate. It might be a good idea to investigate if we can bring TypeScript advantages to the project at this point without too much hassle.

## Tasks

- [x] Strapi setup
- [x] Initial config structure
- [x] .gitignore setup
- [ ] README setup in project root with instructioncs
- [ ] Investigate & potentially implement TS support (not needed)

**Comment by Earlo** [comment]
Mikäs tän Possu vs Myssy keskustelun tilanne oli? 

Eri kannat lokaalisti ja tuotannossa on ainakin huono idea.

**Comment by Earlo** [comment]
Toi TS-juttu on aika toissijainen. Tota Strapia ei käsin tarvii hirveesti koodaa.

**Comment by Earlo** [comment]
Kiinostava kysymys on että minkälaisia tietotyyppejä meillä tulee olemaan strapissa
